from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
sb = KeyboardButton("Student book audios")
wb = KeyboardButton("Workbook audios")

student = ReplyKeyboardMarkup()
s1 = KeyboardButton("Unit 1")
s2 = KeyboardButton("Unit 2")
s3 = KeyboardButton("Unit 3")
s4 = KeyboardButton("Unit 4")
s5 = KeyboardButton("Unit 5")
s6 = KeyboardButton("Unit 6")
s7 = KeyboardButton("Unit 7")
s8 = KeyboardButton("Unit 8")
s9 = KeyboardButton("Unit 9")
s10 = KeyboardButton("Unit 10")
back = KeyboardButton("🔙Back")
student.add(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10)
student.add(back)

workbook = ReplyKeyboardMarkup()
wb1 = KeyboardButton("Workbook Unit 1")
wb2 = KeyboardButton("Workbook Unit 2")
wb3 = KeyboardButton("Workbook Unit 3")
wb4 = KeyboardButton("Workbook Unit 4")
wb5 = KeyboardButton("Workbook Unit 5")
wb6 = KeyboardButton("Workbook Unit 6")
wb7 = KeyboardButton("Workbook Unit 7")
wb8 = KeyboardButton("Workbook Unit 8")
wb9 = KeyboardButton("Workbook Unit 9")
wb10 = KeyboardButton("Workbook Unit 10")
back = KeyboardButton("🔙Back")
workbook.add(wb1, wb2, wb3, wb4, wb5, wb6, wb7, wb8, wb9, wb10)
workbook.add(back)

menu = ReplyKeyboardMarkup()
menu.add(sb)
menu.add(wb)